parameters:
#    cubby_hole_main.example.class: CubbyHole\MainBundle\Example

services:
#    cubby_hole_main.example:
#        class: %cubby_hole_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
