<?php

namespace CubbyHole\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SharingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharingRepository extends EntityRepository
{
}
