parameters:
#    cubby_hole_user.example.class: CubbyHole\UserBundle\Example

services:
#    cubby_hole_user.example:
#        class: %cubby_hole_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
